apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: nexst-staging

images:
  - name: nexst-worker
    newName: ghcr.io/your-org/nexst-worker
    newTag: test

configMapGenerator:
  - name: nexst-worker-config
    behavior: merge
    envs:
      - application.properties
