apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: nexst-staging

images:
  - name: nexst-api
    newName: ghcr.io/your-org/nexst-api
    newTag: test
  - name: nexst-api-migrate
    newName: ghcr.io/your-org/nexst-api-migrate
    newTag: test

configMapGenerator:
  - name: nexst-api-config
    behavior: merge
    envs:
      - application.properties
